debug: false
pvp-protection-time: 60
spawn-kill-timeout: 60
death-message-timeout: 60
hunger-protection-time: 60
newbie-stalker-threshold: 40
end-reset-enabled: false
generate-end-portals: true
pvp-log-threshold: 5
nerf-endermen-drops: false
nerf-pigzombie-drops: false
animal-chunk-cap: 30
muted-words: []